# -*- coding: utf-8 -*-
"""PC01_SI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vbUvj_lnaQd0KYXmM0W35Ve0BKTBsLu
"""

import streamlit as st
import pandas as pd
import numpy as np
import time

st.set_page_config(page_title="Sistema de Gestión de Créditos", layout="wide")
st.title("Sistema de Gestión de Créditos – Caja San Jerónimo")

# Inicialización de base de datos en memoria
if 'solicitudes' not in st.session_state:
    st.session_state.solicitudes = []
if 'pagos' not in st.session_state:
    st.session_state.pagos = []

# MENÚ DE NAVEGACIÓN
menu = st.sidebar.radio("Menú", [
    "🏠 Inicio",
    "📝 Ingreso de Solicitud",
    "🔍 Evaluación Crediticia",
    "✅ Aprobación de Créditos",
    "💳 Gestión de Pagos",
    "📊 Panel de Créditos",
    "⚙️ Configuración del Sistema",
])

# INICIO
if menu == "🏠 Inicio":
    st.header("Bienvenido al Sistema de Gestión de Créditos")
    st.markdown("""
    Este sistema permite simular la gestión completa de solicitudes de crédito, desde su ingreso hasta la evaluación, aprobación y pagos.
    """)
    st.success("Selecciona una opción del menú para comenzar")

# INGRESO DE SOLICITUD
elif menu == "📝 Ingreso de Solicitud":
    st.header("Ingreso de Solicitud de Crédito")
    with st.form("form_solicitud"):
        nombre = st.text_input("Nombre del solicitante")
        dni = st.text_input("DNI")
        monto = st.number_input("Monto solicitado (S/)", 1000, 100000)
        plazo = st.selectbox("Plazo en meses", [6, 12, 24, 36])
        ingresos = st.number_input("Ingresos mensuales (S/)", 500, 20000)
        historial = st.slider("Historial crediticio (0=malo, 10=excelente)", 0, 10, 5)
        enviado = st.form_submit_button("Registrar Solicitud")

        if enviado:
            solicitud = {
                "ID": len(st.session_state.solicitudes) + 1,
                "Nombre": nombre,
                "DNI": dni,
                "Monto": monto,
                "Plazo": plazo,
                "Ingresos": ingresos,
                "Historial": historial,
                "Puntaje FICO": None,
                "Estado": "Pendiente"
            }
            st.session_state.solicitudes.append(solicitud)
            st.success("Solicitud registrada correctamente")

# EVALUACIÓN CREDITICIA
elif menu == "🔍 Evaluación Crediticia":
    st.header("Evaluación Crediticia")
    if not st.session_state.solicitudes:
        st.warning("No hay solicitudes registradas")
    else:
        for solicitud in st.session_state.solicitudes:
            if solicitud["Puntaje FICO"] is None:
                puntaje = min(850, int(300 + solicitud['Historial'] * 50 + (solicitud['Ingresos'] / 500)))
                solicitud["Puntaje FICO"] = puntaje
                solicitud["Estado"] = "Aprobado" if puntaje > 650 else "Rechazado"
        st.success("Evaluación realizada para todas las solicitudes pendientes")
        st.dataframe(pd.DataFrame(st.session_state.solicitudes))

# APROBACIÓN DE CRÉDITOS
elif menu == "✅ Aprobación de Créditos":
    st.header("Estado de Solicitudes")
    df_aprob = pd.DataFrame(st.session_state.solicitudes)
    st.dataframe(df_aprob)

# GESTIÓN DE PAGOS
elif menu == "💳 Gestión de Pagos":
    st.header("Gestión de Pagos de Créditos")
    aprobados = [s for s in st.session_state.solicitudes if s['Estado'] == 'Aprobado']
    if not aprobados:
        st.info("No hay créditos aprobados")
    else:
        opciones = {f"{s['ID']} - {s['Nombre']}": s for s in aprobados}
        seleccionado = st.selectbox("Selecciona un crédito", opciones.keys())
        credito = opciones[seleccionado]
        pago = st.selectbox("Estado del pago", ["Pagado", "Activo", "Vencido"])
        registrar = st.button("Registrar Pago")
        if registrar:
            st.session_state.pagos.append({"ID": credito['ID'], "Nombre": credito['Nombre'], "Estado de Pago": pago})
            st.success("Estado de pago actualizado")
        st.subheader("Historial de Pagos")
        pagos_df = pd.DataFrame([p for p in st.session_state.pagos if p['ID'] == credito['ID']])
        if not pagos_df.empty:
            st.dataframe(pagos_df)
        else:
            st.info("Sin pagos registrados para este crédito")

# PANEL DE CRÉDITOS
elif menu == "📊 Panel de Créditos":
    st.header("Panel de Control de Créditos")
    if st.session_state.solicitudes:
        df = pd.DataFrame(st.session_state.solicitudes)
        st.metric("Total de Solicitudes", len(df))
        st.metric("Aprobados", (df['Estado'] == 'Aprobado').sum())
        st.metric("Rechazados", (df['Estado'] == 'Rechazado').sum())
        st.dataframe(df)
    else:
        st.info("No hay datos para mostrar")

# CONFIGURACIÓN
elif menu == "⚙️ Configuración del Sistema":
    st.header("Configuración y Datos Técnicos")
    st.markdown("""
    ### Requisitos Funcionales:
    - Ingreso de solicitudes con validación
    - Evaluación crediticia automática (modelo FICO)
    - Decisión de aprobación/rechazo
    - Gestión y registro de pagos

    ### Requisitos No Funcionales:
    - Tiempo de respuesta < 5 minutos bajo 200 usuarios simultáneos
    - Integración con CRM y contabilidad (simulado)
    - Interfaz usable e intuitiva
    - Seguridad con cifrado AES-256 y TLS 1.2
    - Portabilidad y mantenibilidad estructurada
    """)