# -*- coding: utf-8 -*-
"""PC01_SI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15vbUvj_lnaQd0KYXmM0W35Ve0BKTBsLu
"""

import streamlit as st
import pandas as pd
import numpy as np

st.set_page_config(page_title="Sistema de Créditos - Caja San Jerónimo", layout="wide")
st.title("Sistema de Gestión de Créditos – Caja San Jerónimo")

# Base de datos en memoria
if 'solicitudes' not in st.session_state:
    st.session_state.solicitudes = []
if 'pagos' not in st.session_state:
    st.session_state.pagos = []

menu = st.sidebar.radio("Menú", [
    "🏠 Inicio",
    "📝 Ingreso de Solicitud",
    "🔍 Evaluación Crediticia",
    "✅ Aprobación de Créditos",
    "💳 Gestión de Pagos",
    "📊 Panel de Créditos",
    "⚙️ Configuración del Sistema"
])

if menu == "🏠 Inicio":
    st.subheader("Bienvenido al sistema")
    st.markdown("Este sistema simula la gestión de créditos de Caja San Jerónimo.")
    st.markdown("_Desarrollado por: Dr. Michael Quinteros_")


elif menu == "📝 Ingreso de Solicitud":
    st.subheader("Registrar nueva solicitud")
    with st.form("form_solicitud"):
        nombre = st.text_input("Nombre")
        dni = st.text_input("DNI")
        monto = st.number_input("Monto solicitado", 1000, 100000)
        plazo = st.selectbox("Plazo (meses)", [6, 12, 24, 36])
        ingresos = st.number_input("Ingresos mensuales", 500, 20000)
        historial = st.slider("Historial crediticio (0-10)", 0, 10, 5)
        enviar = st.form_submit_button("Registrar")
        if enviar:
            st.session_state.solicitudes.append({
                'ID': len(st.session_state.solicitudes) + 1,
                'Nombre': nombre,
                'DNI': dni,
                'Monto': monto,
                'Plazo': plazo,
                'Ingresos': ingresos,
                'Historial': historial,
                'Puntaje FICO': None,
                'Estado': 'Pendiente'
            })
            st.success("Solicitud registrada")


elif menu == "🔍 Evaluación Crediticia":
    st.subheader("Evaluación de solicitudes")
    for solicitud in st.session_state.solicitudes:
        if solicitud['Puntaje FICO'] is None:
            fico = min(850, int(300 + solicitud['Historial'] * 50 + (solicitud['Ingresos'] / 500)))
            solicitud['Puntaje FICO'] = fico
            solicitud['Estado'] = 'Aprobado' if fico > 650 else 'Rechazado'
    st.success("Evaluación realizada")

    st.dataframe(pd.DataFrame(st.session_state.solicitudes))


elif menu == "✅ Aprobación de Créditos":
    st.subheader("Solicitudes registradas")
    st.dataframe(pd.DataFrame(st.session_state.solicitudes))


elif menu == "💳 Gestión de Pagos":
    st.subheader("Gestión de pagos")
    aprobados = [s for s in st.session_state.solicitudes if s['Estado'] == 'Aprobado']
    if aprobados:
        opciones = {f"{s['ID']} - {s['Nombre']}": s for s in aprobados}
        seleccion = st.selectbox("Selecciona crédito", opciones.keys())
        pago_estado = st.selectbox("Estado de pago", ["Pagado", "Activo", "Vencido"])
        if st.button("Registrar Pago"):
            st.session_state.pagos.append({
                'ID': opciones[seleccion]['ID'],
                'Nombre': opciones[seleccion]['Nombre'],
                'Estado de Pago': pago_estado
            })
            st.success("Pago registrado")
        pagos_df = pd.DataFrame([p for p in st.session_state.pagos if p['ID'] == opciones[seleccion]['ID']])
        st.subheader("Historial de Pagos")
        st.dataframe(pagos_df)
    else:
        st.info("No hay créditos aprobados")


elif menu == "📊 Panel de Créditos":
    st.subheader("Panel de resumen")
    total = len(st.session_state.solicitudes)
    aprobados = sum(s['Estado'] == 'Aprobado' for s in st.session_state.solicitudes)
    rechazados = sum(s['Estado'] == 'Rechazado' for s in st.session_state.solicitudes)
    st.metric("Total de solicitudes", total)
    st.metric("Aprobadas", aprobados)
    st.metric("Rechazadas", rechazados)
    st.dataframe(pd.DataFrame(st.session_state.solicitudes))



elif menu == "⚙️ Configuración del Sistema":
    st.subheader("Configuración del Sistema")
    st.markdown("""
    ### Requisitos Funcionales:
    - Ingreso de solicitudes con validación
    - Evaluación crediticia automática (modelo FICO)
    - Decisión de aprobación/rechazo
    - Gestión y registro de pagos

    ### Requisitos No Funcionales:
    - Tiempo de respuesta < 5 minutos bajo 200 usuarios simultáneos
    - Interfaz usable e intuitiva
    - Seguridad con cifrado AES-256 y TLS 1.2
    - Portabilidad y mantenibilidad estructurada
    """)